model:
  name: mistralai/Mistral-7B-Instruct-v0.2
  backend: hf
  device: 0
  max_new_tokens: 512
  temperature: 0.7

data:
  base_summary_dir: data/base_summaries/
  checkpoint_dir: data/checkpoints/
  improved_summary_dir: data/improved_summaries/
  results_dir: results/


iteration:
  max_iterations: 5
  rouge_metric: rouge-l
  stopping_criterion: rouge-l
  tolerance: 0.01


